'use strict';

// ── Validation ──
function validateBookParams(input) {
  const errors = [];
  if (!input.book || typeof input.book !== 'string' || input.book.trim().length === 0) {
    errors.push('book 字段是必填的，且不能为空');
  } else if (input.book.trim().length > 200) {
    errors.push('book 字段长度不能超过 200 个字符');
  }
  const author = input.author ? String(input.author).trim() : '';
  if (author.length > 100) {
    errors.push('author 字段长度不能超过 100 个字符');
  }
  return { valid: errors.length === 0, errors, book: (input.book || '').trim(), author };
}

// ── JSON Repair ──
function repairJSON(raw) {
  let text = raw.trim();
  // Strip markdown code block wrappers
  text = text.replace(/^```(?:json)?\s*\n?/i, '').replace(/\n?```\s*$/, '');
  // Remove trailing commas before } or ]
  text = text.replace(/,(\s*[}\]])/g, '$1');
  return text;
}

// ── Template ──
function fillTemplate(parsed) {
  const d = new Date().toISOString().split('T')[0];
  const kp = parsed.key_points || [];
  const ai = parsed.action_items || [];
  const ns = parsed.next_suggestions || [];

  const lines = [
    '---',
    `title: "📖 《${parsed.book_title || ''}》——${parsed.one_line_summary || ''}"`,
    `author: ${parsed.author || ''}`,
    `category: ${parsed.category || ''}`,
    `tags: ${JSON.stringify(parsed.tags || [])}`,
    `date: ${d}`,
    'source: manual',
    `next_suggestion: ${JSON.stringify(ns)}`,
    '---',
    '',
    `# 📖 《${parsed.book_title || ''}》——${parsed.one_line_summary || ''}`,
    '',
    `> **为什么推荐这本书？** ${parsed.recommendation_reason || ''}`,
    '',
    '---',
    '',
    '## 🎯 核心框架',
    '',
    `${parsed.core_framework || ''}`,
    '',
    '---',
    '',
    '## 📌 五个核心知识点',
    '',
  ];

  for (let i = 0; i < kp.length; i++) {
    const p = kp[i];
    if (!p || !p.title) continue;
    lines.push(
      `### ${i + 1}️⃣ ${p.title}`,
      '',
      p.content || '',
      '',
      `> 🔑 **关键洞见：** ${p.insight || ''}`,
      '',
      `🫁 **试试看：** ${p.practice || ''}`,
      '',
    );
  }

  lines.push(
    '---',
    '',
    '## 💎 一句话记住这本书',
    '',
    `> ${parsed.golden_quote || ''}`,
    '',
    '---',
    '',
    '## 🛠️ 今日行动清单',
    '',
    ...ai.map((i) => `- [ ] ${i}`),
    '',
    '---',
    '',
    '## 📎 关联推荐',
    '',
    '| 方向 | 推荐书籍 | 为什么关联 |',
    '|------|---------|-----------|',
    ...ns.map((s) => {
      const icon = s.direction === '横向拓展' ? '🔄 横向拓展' : s.direction === '深度延伸' ? '↗️ 深度延伸' : '➡️ 实用落地';
      const cleanBook = (s.book || '').replace(/^《/, '').replace(/》$/, '');
      return `| ${icon} | 《${cleanBook}》 | ${s.reason} |`;
    }),
    '',
    '---',
    '',
    `*generated by 拆书工作流 · ${d}*`,
  );

  const md = lines.join('\n');
  const safeName = (parsed.book_title || '未命名').replace(/[\\/:*?"<>|]/g, '-');
  return {
    markdown: md,
    file_name: `${d}-${safeName}-chaishu`,
    date: d,
    book_title: parsed.book_title,
    author: parsed.author,
    tags: parsed.tags,
    category: parsed.category,
    next_suggestions: ns,
    golden_quote: parsed.golden_quote,
    key_points: parsed.key_points,
  };
}

// ── Self-review ──
function validateContent(markdown, _bookTitle) {
  const issues = [];
  if (markdown.includes('�')) {
    const count = (markdown.match(/�/g) || []).length;
    issues.push(`发现 ${count} 个乱码字符`);
  }
  if (!markdown.includes('## 🎯 核心框架')) issues.push('缺少核心框架');
  if (!markdown.includes('## 📌')) issues.push('缺少核心知识点');
  if (!markdown.includes('## 💎 一句话记住')) issues.push('缺少金句');
  if (!markdown.includes('## 🛠️ 今日行动')) issues.push('缺少行动清单');
  if (markdown.length < 1000) issues.push(`内容过短 (${markdown.length} chars)`);

  if (issues.length > 0) {
    return { ok: false, issues };
  }
  return { ok: true, issues: [] };
}

// ── Format for Feishu ──
function formatForFeishu(md) {
  let t = md.replace(/^---\n[\s\S]*?\n---\n*/, ''); // strip frontmatter

  // Headers → bold text
  t = t.replace(/^####? (.+)$/gm, '\n**$1**\n');
  t = t.replace(/^### (.+)$/gm, '\n**$1**\n');
  t = t.replace(/^## (.+)$/gm, '\n\n**$1**\n');
  t = t.replace(/^# (.+)$/gm, '\n\n**$1**\n');

  // Blockquotes → clean format
  t = t.replace(/^> 🔑 \*\*(.+?)\*\*\s*/gm, '🔑 **$1** ');
  t = t.replace(/^> \*\*(.+?)\*\*\s*/gm, '💬 **$1** ');
  t = t.replace(/^> (.+)$/gm, '$1');

  // Horizontal rules
  t = t.replace(/^---$/gm, '━━━━━━━━━━━━━━━━');

  // Task lists → checkmark
  t = t.replace(/^- \[ \] (.+)$/gm, '✅ $1');

  // Tables → simplified list
  t = t.replace(/\| (.+?) \| 《(.+?)》 \| (.+?) \|/g, '• **《$2》** — $3');

  // Table headers
  t = t.replace(/^\| .+ \|$/gm, '');
  t = t.replace(/^\|[-| ]+\|$/gm, '');

  // Clean up
  t = t.replace(/\n{3,}/g, '\n\n');
  t = t.replace(/\*generated by.*$/m, '');

  return t.trim();
}

// ── Format for 小红书 ──
function formatXHS(parsed) {
  const kp = parsed.key_points || [];
  const ai = parsed.action_items || [];
  const tags = (parsed.tags || []).map((tag) => `#${tag}`).join(' ');

  const lines = [
    `📖 **《${parsed.book_title || ''}》**`,
    `*${parsed.one_line_summary || ''}*`,
    '',
    '💡 **为什么推荐这本书？**',
    `${parsed.recommendation_reason || ''}`,
    '',
    '🎯 **核心框架**',
    `${parsed.core_framework || ''}`,
    '',
    '📌 **核心知识点**',
    '',
  ];

  for (let i = 0; i < Math.min(kp.length, 5); i++) {
    const p = kp[i];
    lines.push(
      `**${i + 1}️⃣ ${p.title || ''}**`,
      `${(p.content || '').slice(0, 200)}`,
      `> 💬 *${p.insight || ''}*`,
      '',
    );
  }

  lines.push(
    '💎 **一句话记住**',
    `> ${parsed.golden_quote || ''}`,
    '',
    '🛠️ **今日行动**',
    ...ai.slice(0, 3).map((i) => `✅ ${i}`),
    '',
    tags,
  );

  return lines.join('\n');
}

module.exports = {
  validateBookParams,
  repairJSON,
  fillTemplate,
  validateContent,
  formatForFeishu,
  formatXHS,
};
